# Site settings
title: theme-leo
subtitle: software libero, cultura libera
email: leopoldotosi1[at]google[dot]com
#baseurl: "http://0.0.0.0:4000/"
baseurl: ""
#url: "http://127.0.0.1:4000/poldoit"
#url: "https://leopoldotosi.github.io/poldoit"
url: "https://leopoldotosi.github.io"
github_username: leopoldotosi
author: "leopoldo tosi"
street_address: "via bari 8"
city: Milano
state: IT
locale: it
feed:
  path: atom.xml


# Build settings
markdown: kramdown
#permalink: /themesleo
#theme: jekyll-theme-dinky
plugins:
  - jekyll-admin
  - jekyll-feed
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-lunr-js-search 
# - github-pages
#lunr_search:
# excludes: [rss.xml, atom.xml] 
#   min_length: 2
# stopwords: "stopwords.txt"
# js_dir: "assets/js" 
# paginate: 6
